server:
  port: 8081

spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce
          jwk-set-uri: http://localhost:8080/realms/ecommerce/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:8080
  realm: ecommerce
  resource: auth-service
  credentials:
    secret: your-client-secret-key
  public-client: false
  bearer-only: true
  principal-attribute: preferred_username

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
