global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "spring-boot-apps"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "api-gateway:8080"
          - "product-service:8081"
          - "order-service:8082"
          - "inventory-service:8083"
          - "payment-service:8084"
          - "user-service:8085"
