package com.ironsoftware.reportingservice.model;

public enum ReportType {
    SALES_REPORT,
    INVENTORY_REPORT,
    USER_ACTIVITY_REPORT,
    FINANCIAL_REPORT,
    PRODUCT_PERFORMANCE_REPORT,
    ORDER_ANALYTICS_REPORT,
    CUSTOMER_BEHAVIOR_REPORT,
    DELIVERY_PERFORMANCE_REPORT,
    PAYMENT_ANALYTICS_REPORT,
    SYSTEM_HEALTH_REPORT
}
