apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-pipeline-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-pipeline-service
  template:
    metadata:
      labels:
        app: data-pipeline-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8093"
    spec:
      containers:
        - name: data-pipeline-service
          image: ironsoftware/data-pipeline-service:latest
          ports:
            - containerPort: 8093
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8888
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8093
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8093
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: data-pipeline-service
spec:
  ports:
    - port: 8093
      targetPort: 8093
  selector:
    app: data-pipeline-service
