server:
  port: 8090

spring:
  application:
    name: cart-service
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 60000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: -1ms

# Cart Configuration
cart:
  expiration: 604800 # 7 days in seconds
  max-items: 50
  price-update-interval: 300 # 5 minutes in seconds

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
