server:
  port: 8087

spring:
  application:
    name: analytics-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analytics-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

analytics:
  spark:
    master: local[*]
    app-name: ecommerce-analytics
  influxdb:
    url: http://localhost:8086
    database: analytics_metrics
    retention-policy: autogen
    batch-size: 100
    flush-duration: 1000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
