server:
  port: 8088

spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/review-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: review-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Sentiment Analysis Configuration
sentiment:
  model:
    path: /models/sentiment-model
    language: english
    batch-size: 100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
